In [1]:
#adding two numbers
num1= 3
num2=2
#sum of num1 and num2
sum = num1+num2
#show sum
print (sum)

5

In [2]:
int (3.77)

3

In [3]:
float (3.77)

3.77

In [2]:
x = int(input('Enter the first nuber to add'))
y = int(input('Enter the second number to add'))
print(f'The sum of the numbers is: {x+y}')

Enter the first nuber to add 8
Enter the second number to add 4

The sum of the numbers is: 12

In [3]:
pip install pandas

Collecting pandas
  Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hadul\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\hadul\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl (11.5 MB)
Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002B26464D970>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network')': /packages/16/2e/86f24451c2d530c88daf997cb8d6ac622c1d40d19f5a031ed68a4b73a374/numpy-1.26.4-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002B2647AE1E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/16/2e/86f24451c2d530c88daf997cb8d6ac622c1d40d19f5a031ed68a4b73a374/numpy-1.26.4-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002B26464E300>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/16/2e/86f24451c2d530c88daf997cb8d6ac622c1d40d19f5a031ed68a4b73a374/numpy-1.26.4-cp312-cp312-win_amd64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 472, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1249, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1105, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\operations\prepare.py", line 552, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\operations\prepare.py", line 467, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\network\download.py", line 183, in __call__
    for chunk in chunks:
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    with self._error_catcher():
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "C:\Users\hadul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
x=5
y= "John"
print(x)
print(y)

5
John

In [3]:
x=4
y='shahid'
z=5.987
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'str'>
<class 'float'>

In [5]:
x=1 #int
y=2.8 #float
z=1j #complex
#convert from int to float
a=float(x)
#convert from float to int
b=int(y)
#convert from int to complex
c=complex(x)
print (a)
print (b)
print (c)
print (type(a))
print (type(b))
print (type(c))

1.0
2
(1+0j)
<class 'float'>
<class 'int'>
<class 'complex'>

In [9]:
#Length of string
a= "My name is Andy"
print(len(a))

15

In [16]:
#Slicing Strings
b="Hello, World!"
S=b[2:5]
print(S)

llo

In [17]:
#Slicing Strings From start
b="Hello, World!"
print(b[:5])

Hello

In [18]:
#Slicing Strings From end
b="Hello, World!"
print(b[2:])

llo, World!

# ASSIGNMENT

In [29]:
#Creating string variable with sentence of choice
g= "Love coding in Python"

In [30]:
#Print the first word of the sentence
print (g[:4])

Love

In [31]:
#Print the last word in the sentence
print (g[15:21])

Python

In [32]:
#Print substring that includes 5th to 10th characters of the sentence 
print (g[5:11])

coding

In [33]:
#Print sentence in reverse 
print(g[::-1])

nohtyP ni gnidoc evoL

In [6]:
tuple= (1,2,3,4,5,6,7,8)
b=(tuple[2:6:2])
print (b)

(3, 5)

# ASSIGNMENT TWO

In [85]:
#Assigning a sentence of own choice 
a="Slicing String Variable using Python"

In [61]:
#Slicing with start and stop indices
e=(a[2:13])
print(e)

icing Strin

In [62]:
#Slicing with start,stop and step indices
f=(a[2:13:3])
print(f)

inSi

In [63]:
#Slicing from the begining to a specific position
h=(a[:13])
print(h)

Slicing Strin

In [64]:
#Slicing from a specific position to the end 
j=(a[2:])
print (j)

icing String Variable using Python

In [65]:
#Slicing the entire string
k=(a[:])
print(k)

Slicing String Variable using Python

In [66]:
#Slicing with a negative step to reverse
l=(a[::-1])
print(l)

nohtyP gnisu elbairaV gnirtS gnicilS

In [100]:
#Slicing using negative indices
print(a[-13:-2])

 using Pyth

In [2]:
#String to upper case
a="Hello, World!"
B=a.upper()
print(B)

HELLO, WORLD!

In [3]:
#String to lower case
a="Hello, World!"
print(a.lower())

hello, world!

In [5]:
#Replacing String
a= "Coding in Python"
B= a.replace("C","B")
print(B)

Boding in Python

In [11]:
#String Concatenation
a= "Coding"
b= "Python"
c=a+" "+b
print(c)

Coding Python

In [15]:
#string format
age=36
txt="My name is John and I am {}"
D=txt.format(age)
print(D)

My name is John and I am 36

In [17]:
quantity=3
itemno=567
price=49.95
myorder= "I want {} pieces of item {} for {} dollars."
print(myorder.format(quantity, itemno,price))

I want 3 pieces of item 567 for 49.95 dollars.

In [19]:
#Add two Numbers with user input
#Input numbers
num1=input('Enter the first nuber to add:')
num2=input('Enter the second number to add:')
# Add two numbers
sum=float(num1)+float(num2)
#Display sum
print('The sum of {0} and {1} is {2}'.format(num1,num2,sum))

Enter the first nuber to add: 3
Enter the second number to add: 4

The sum of 3 and 4 is 7.0

In [20]:
#Lists
list=[1,2,3,4,5,6,7]
print(list[0])
print(list[1])
print(list[2])
print(list[3])
#slicing the elements
print(list[0:6])
print(list[:])
print(list[2:5])
print(list[1:6:2])

1
2
3
4
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]
[3, 4, 5]
[2, 4, 6]

In [21]:
list=[1,2,3,4,5]
print(list[-1])
print(list[-3:])
print(list[:-1])
print(list[-3:-1])

5
[3, 4, 5]
[1, 2, 3, 4]
[3, 4]

In [22]:
list=[1,2,3,4,5,6]
print(list)
#It will assign value to the second index
list[2]= 10;
print(list)
list[1:3]=[89,78]
print(list)
list[-1]=25
print(list)

[1, 2, 3, 4, 5, 6]
[1, 2, 10, 4, 5, 6]
[1, 89, 78, 4, 5, 6]
[1, 89, 78, 4, 5, 25]

In [24]:
#appending
thislist=["red","black", "white","yellow","blue"]
thislist.append("orange")
print(thislist)

['red', 'black', 'white', 'yellow', 'blue', 'orange']

In [25]:
#inserting
thislist=["red","black", "white","yellow","blue"]
thislist.insert(0,"orange")
print(thislist)

['orange', 'red', 'black', 'white', 'yellow', 'blue']

In [29]:
#removing items
thislist=["red","black", "white","yellow","blue"]
thislist.remove("red")
print(thislist)

['black', 'white', 'yellow', 'blue']

In [27]:
thislist=["red","black", "white","yellow","blue"]
thislist.pop(3)
print(thislist)

['red', 'black', 'white', 'blue']

In [30]:
thislist=["red","black", "white","yellow","blue"]
thislist.clear()
print(thislist)

[]

# ASSIGNMENT THREE

In [20]:
#Create a list with 5 elements
fruits = ["banana", "mango", "orange", "apple", "grapes"]

In [21]:
#Print the first and the last element of the list
print (fruits[0]) #the first element is not one in code rather it starts at 0
print (fruits [4])

banana
grapes

In [22]:
#Modifying an element in our list
fruits[2]= "blueberry"; #changes element in position 2 to blueberry 
print (fruits)

['banana', 'mango', 'blueberry', 'apple', 'grapes']

In [23]:
#Append elements
fruits.append("fig") #this will add fig to the list
print (fruits)

['banana', 'mango', 'blueberry', 'apple', 'grapes', 'fig']

In [24]:
#Remove elements 
fruits.remove("mango") #mango will be removed from the list
print (fruits)

['banana', 'blueberry', 'apple', 'grapes', 'fig']

In [32]:
#Slicibg the list
print (fruits[0:3]) # Will display the first 3 elements
print (fruits[2:]) # Will only show elements from position 2 when starting to count at 0

['banana', 'blueberry', 'apple']
['apple', 'grapes', 'fig']

In [35]:
#Concatenate a list
vegetables = ["carrot", "broccoli", "asparagus"] #Creating a new list
#Concatenation of fruits and vegetables lists into a new list (food)
food = fruits + vegetables #this will merge the whole list of fruits and vegetables into one
print (food)

['banana', 'blueberry', 'apple', 'grapes', 'fig', 'carrot', 'broccoli', 'asparagus']

In [37]:
#Creating a nested list
nested_list = [1,2,['a','b','c'],4,5] 
print(nested_list[2]) # this will print the second element in the list. Start counting from 0

['a', 'b', 'c']

In [38]:
#Using list comprehension
squares = [x**2 for x in range(11)] # Will print a list of squares from 0 to 10
#Note, range is 11 and not 10 since we start counting from 0 that means 10 will actually be our 11th iteam
print (squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

# Tuple

In [40]:
#A simple tuple
thistuple= ("green" , "blue", "black")
print (thistuple)

('green', 'blue', 'black')

In [41]:
#length of a tuple
print (len(thistuple))

3

In [43]:
#Converting tuple into list to be able to change it
x=("apple", "banana", "cherry")
y=list(x)
y[1] ="kiwi"
x= tuple(y)
print (x)

('apple', 'kiwi', 'cherry')

In [47]:
#appending a tuple
x=("apple", "banana", "cherry")
y=list(x) #convert the tuple to list
y.append("mango") 
x=tuple(y) #after appending convert it back to tuple
print (x)

('apple', 'banana', 'cherry', 'mango')

In [46]:
#adding a tuple to a tuple
thistuple= ("green" , "blue", "black")
y=("white",)
thistuple+=y
print (thistuple)

('green', 'blue', 'black', 'white')

# PYTHON SETS

In [49]:
# Creating a set
thisset= {"green", "black", "blue"} # Uses {} brackets 
print (thisset)

{'green', 'blue', 'black'}

In [51]:
# Duplicate values are ignored
thisset= {"green", "black", "blue", "green"}
print (thisset)

{'green', 'blue', 'black'}

In [55]:
#Looping through a set to print the values. values cannot be accessed using indexes
thisset= {"green", "black", "blue"}
for x in thisset:
    print (x)

green
blue
black

In [54]:
#adding to a set
thisset= {"green", "black", "blue"}
thisset.add("orange")
print (thisset)

{'orange', 'green', 'blue', 'black'}

In [56]:
#usisng update to add a set into another set
thisset= {"green", "black", "blue"}
colours={"brown", "red", "purple"}
thisset.update(colours)
print (thisset)

{'blue', 'red', 'purple', 'brown', 'green', 'black'}

In [58]:
#removing an item from a set
thisset= {"green", "black", "blue"}
thisset.remove("black")
print(thisset)

{'green', 'blue'}

# DICTIONARIES

In [61]:
# Creating s dictionary
thisdict= {
    "brand":"Ford",
    "model":"Mustang",
    "year":1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [63]:
#calling a value
print(thisdict["brand"])

Ford

In [64]:
thisdict= {
    "brand":"Ford",
    "model":"Mustang",
    "year":1964,
    "year":2020
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2020}

In [67]:
#determining how many items a dictionary has
s=len(thisdict)
print(s)

3

In [71]:
#Getting the list of all keys
thisdict= {
    "brand":"Ford",
    "model":"Mustang",
    "year":1964
}
x=thisdict.keys()
print(x) #before changing
thisdict["colour"]="white" #adding a key and value to the dictionary
print(x) #after the change

dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'colour'])

In [73]:
#Getting the list of values
thisdict= {
    "brand":"Ford",
    "model":"Mustang",
    "year":1964
}
x=thisdict.values()
print(x) #before the change
thisdict["year"]=2020 #changing a value to the dictionary
print (x) # after the change

dict_values(['Ford', 'Mustang', 1964])
dict_values(['Ford', 'Mustang', 2020])

In [75]:
#changing values
thisdict= {
    "brand":"Ford",
    "model":"Mustang",
    "year":1964
}
thisdict ["year"]="2018"
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': '2018'}

In [76]:
thisdict= {
    "brand":"Ford",
    "model":"Mustang",
    "year":1964
}
print(thisdict)
thisdict.update({"year":2020})
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
{'brand': 'Ford', 'model': 'Mustang', 'year': 2020}

# ASSIGNMENT FOUR

In [8]:
#create a dictionary
university = {
    "name": "USIU", # give the keys and values of your dictionary
    "location":"Nairobi",
    "students":{
        "student1":{
            "name":"Andy",
            "age": 21,
            "major":"Data Science and Analytics"
        },
        "Student2":{
            "name":"Mike",
            "age":22,
            "major":"Software Engineering"
        }
    }
}
print (university) # display the output of the dictionary
#Accessing the major of student1
major= university["students"]["student1"]["major"] #defing the position of student one.
print(major) #shows the major of student1

{'name': 'USIU', 'location': 'Nairobi', 'students': {'student1': {'name': 'Andy', 'age': 21, 'major': 'Data Science and Analytics'}, 'Student2': {'name': 'Mike', 'age': 22, 'major': 'Software Engineering'}}}
Data Science and Analytics

# IF STATEMENTS

In [7]:
#using if statements and elif
a=34 
b=35
if b>a:
    print("b is greater than a") #basic if statement
elif a==b:
    print ("a and b are eaqual") # using elif
else:
    print("a is greater than b") #using else

b is greater than a

In [8]:
#else without elif
a=200
b=33
if b>a:
    print("b is greater tha a")
else:
    print("b is not greater than a")

b is not greater than a

In [9]:
#short hand if...else
a=2
b=330
print ("A")if a>b else print ("B")

B

In [10]:
#multiple else statements of the same line
a = 330
b = 330
print ("A") if a> b else print ("=") if a==b else print ("B")

=

In [11]:
#Using and
a=200
b=33
c=500
if a>b and c>a:
    print ("Both conditions are true")

Both conditions are true

In [12]:
#using or
a=200
b=33
c=500
if a>b or c>a:
    print ("At least one conditions is true")

At least one conditions is true

In [20]:
# Nested if statements
x=40
if x>10:
    print ("Above ten")
    if x>20:
        print ("and also above 20!")
    else:
        print ("but not above 20")
else:
    print ("is less than ten")

Above ten
and also above 20!

In [23]:
# Checking is a number is positive or negative
num=float(input("Enter a number:"))
if num >=0:
    if num ==0:
        print ("Zero")
    else:
        print ("Positive number")
else:
    print ("Negative number")

Enter a number: -4

Negative number

In [30]:
#an if statement with a list
list= [4,3,5,6,7]
if list[0]>list[1]:
    print ("success")
else:
    print ("Hello")

success

# WHILE LOOP

In [1]:
#using while loops
i=1
while i<6:
    print (i)
    i+=1

1
2
3
4
5

In [2]:
#adding a break statement
i=1
while i<6:
    print (i)
    if i ==3:
        break
    i+=1

1
2
3

In [4]:
i = 0
while i<6:
    i+=1
    if i ==3:
        continue
    print(i)

1
2
4
5
6

In [5]:
# ussing the else statement 
i=0
while i<6:
    print (i)
    i+=1
else:
    print("i is no longer less than 6")

0
1
2
3
4
5
i is no longer less than 6

In [11]:
list = [4,3,5,6,7,8]
s=8
i=0
while i<len(list):
    if list[i] == s:
        print ("found successfully",list[i])
        break
    i+=1
else:
    print("no match")

found successfully 8

# CSV FILE: Importing and reading

In [1]:
# using dictreader()
import csv
with open('sales_data.csv') as csvfile: 
    m=list(csv.DictReader(csvfile))
print(m[:3])

[{'Month': 'January', 'Units Sold': '100', 'Price per Unit': '50', 'Total Revenue': '5000'}, {'Month': 'February', 'Units Sold': '120', 'Price per Unit': '50', 'Total Revenue': '6000'}, {'Month': 'March', 'Units Sold': '140', 'Price per Unit': '50', 'Total Revenue': '7000'}]

In [2]:
#Using reader()
import csv
with open('sales_data.csv') as csvfile: 
    m=list(csv.reader(csvfile))
print(m[:3])

[['Month', 'Units Sold', 'Price per Unit', 'Total Revenue'], ['January', '100', '50', '5000'], ['February', '120', '50', '6000']]

In [17]:
#Using DictWriter()
import csv
with open('names.csv', 'w',newline='') as csvfile: 
    fieldnames=['first_name','last_name']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerow({'first_name':'Andy','last_name':'Hadulo'})
    writer.writerow({'first_name':'Sofia','last_name':'Queen'})
    writer.writerow({'first_name':'Jane','last_name':'Achieng'})
print(writer)

<csv.DictWriter object at 0x00000245449DE5A0>

# ASSIGNMENT 6

In [68]:
# Imputing csv file
students = [] #an empty list to collect data
import csv
with open ('students_scores.csv') as csvfile:
    m=list(csv.DictReader(csvfile))
    for row in m:
        students.append(row) #after data is read stor it in the students list
print(m)

[{'ï»¿Name': 'Alice', 'Math': '85', 'Science': '90', 'English': '88'}, {'ï»¿Name': 'Bob', 'Math': '78', 'Science': '81', 'English': '85'}, {'ï»¿Name': 'Charlie', 'Math': '95', 'Science': '89', 'English': '92'}]

In [60]:
# We culculate the averege of each student
for student in students:
    math_score = float (student['Math'])
    science_score= float(student['Science'])
    eng_score= float(student['English'])
    #We culculate the average now
    average = (math_score + science_score + eng_score) / 3
    student['Average']= average 
    print(student['Average'])

87.66666666666667
81.33333333333333
92.0

In [67]:
   # We output the new CSV file.
with open('students_averages.csv', 'w', newline='') as filecsv:
    fieldnames=['Name','Average']
    writer = csv.DictWriter(filecsv, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerow({'Name': 'Alice', 'Average': 87.67})
    writer.writerow({'Name': 'Bob', 'Average': 81.33})
    writer.writerow({'Name': 'Charlie', 'Average': 92.0})

In [ ]:
#Looping through rows

f= open('names.csv')

In [ ]:
#Extracting Information from csv file

# PANDAS

In [4]:
#Series 
import pandas as pd
names = ['ian', 'linda', 'susan']
pd.Series(names)

0      ian
1    linda
2    susan
dtype: object

In [5]:
# specifying the index
names = ['ian', 'linda', 'susan']
pd.Series(names, index=['student_1', 'student_2', 'student_3'])

student_1      ian
student_2    linda
student_3    susan
dtype: object

In [13]:
# series constructor to convert a dictionary
classes={'room_a':'math', 'room_b': 'science', 'room_c':'english'}
s=pd.Series(classes)
s.index #to get the indext values

Index(['room_a', 'room_b', 'room_c'], dtype='object')

In [14]:
names = ['ian', 'linda', None]
pd.Series(names)

0      ian
1    linda
2     None
dtype: object

In [15]:
number=[12,34,56,34,None]
pd.Series(number)

0    12.0
1    34.0
2    56.0
3    34.0
4     NaN
dtype: float64

In [4]:
# The file sales.csv
import pandas as pd #Importing pands
df = pd.read_csv ('sales.csv') # read the csv file into the dataframe
grouped_df = df.groupby('Region')['Sales'].sum().reset_index()#grouping the data based on region and calculating the sum of each region
#Print the result of the data frame
print (grouped_df)

  Region  Sales
0   East  15050
1  North  18300
2  South  14100
3   West  16550

In [9]:
#the file employees.csv
dframe = pd.read_csv ('employees.csv') # read the csv into the data frame
mean_salary = dframe['Salary'].mean # working out the mean of the salary 
#filling the missing values of salary with the mean of the salary 
dframe['Salary'].fillna(mean_salary, inplace=True)
 
 #printing the result of the data frame

print(dframe)

                  Name Department  Salary
0             John Doe         HR   50000
1           Jane Smith         IT   60000
2      Michael Johnson    Finance   55000
3          Emily Davis  Marketing   52000
4        Jessica Brown         IT   62000
5         David Wilson         HR   48000
6         Laura Taylor    Finance   53000
7      Daniel Anderson         IT   61000
8         Sarah Thomas  Marketing   51000
9          James Moore         HR   49000
10        Lisa Jackson    Finance   54000
11       Robert Harris         IT   63000
12          Mary Clark  Marketing   50000
13       William Lewis         HR   47000
14   Patricia Robinson    Finance   56000
15  Christopher Walker         IT   64000
16        Barbara Hall  Marketing   53000
17       Matthew Young         HR   50000
18     Elizabeth Allen    Finance   57000
19         Joshua King         IT   65000
20        Susan Wright  Marketing   52000
21        Andrew Scott         HR   48000
22         Karen Green    Finance   55000
23        Joseph Adams         IT   66000
24         Nancy Baker  Marketing   51000
25        Brian Nelson         HR   49000
26       Sandra Carter    Finance   58000
27      Kevin Mitchell         IT   67000
28         Donna Perez  Marketing   50000
29      Edward Roberts         HR   46000
30     Margaret Turner    Finance   59000
31     George Phillips         IT   68000
32      Betty Campbell  Marketing   53000
33      Charles Parker         HR   47000
34         Helen Evans    Finance   60000
35      Steven Edwards         IT   69000
36     Dorothy Collins  Marketing   51000
37      Thomas Stewart         HR   45000
38       Ashley Morris    Finance   61000
39     Kimberly Rogers         IT   70000
40           Paul Reed  Marketing   50000
41        Cynthia Cook         HR   46000
42         Ryan Morgan    Finance   62000
43         Angela Bell         IT   71000
44        Larry Murphy  Marketing   52000
45        Karen Bailey         HR   44000
46      Jeffrey Rivera    Finance   63000
47      Deborah Cooper         IT   72000
48  Melissa Richardson  Marketing   51000

# Numpy

In [1]:
import numpy as np

 

# Define a structured data type

dtype = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

 

# Create a structured array

data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.0), ('Cathy', 22, 45.8)], dtype=dtype)

 

# Access the entire array

print("Structured Array:\n", data)

 

# Access specific fields

print("\nNames:", data['name'])

print("Ages:", data['age'])

print("Weights:", data['weight'])

Structured Array:
 [('Alice', 25, 55.5) ('Bob', 30, 85. ) ('Cathy', 22, 45.8)]

Names: ['Alice' 'Bob' 'Cathy']
Ages: [25 30 22]
Weights: [55.5 85.  45.8]

In [2]:
import numpy as np

 

# Define a structured data type

dtype = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

 

# Create a structured array first

data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.0), ('Cathy', 22, 45.8)], dtype=dtype)

 

# Convert structured array to a record array

rec_data = data.view(np.recarray)

 

# Access the entire array

print("Record Array:\n", rec_data)

 

# Access specific fields using both dictionary-style and attribute-style

print("\nNames (dictionary-style):", rec_data['name'])

print("Names (attribute-style):", rec_data.name)

print("Ages (dictionary-style):", rec_data['age'])

print("Ages (attribute-style):", rec_data.age)

print("Weights (dictionary-style):", rec_data['weight'])

print("Weights (attribute-style):", rec_data.weight)

Record Array:
 [('Alice', 25, 55.5) ('Bob', 30, 85. ) ('Cathy', 22, 45.8)]

Names (dictionary-style): ['Alice' 'Bob' 'Cathy']
Names (attribute-style): ['Alice' 'Bob' 'Cathy']
Ages (dictionary-style): [25 30 22]
Ages (attribute-style): [25 30 22]
Weights (dictionary-style): [55.5 85.  45.8]
Weights (attribute-style): [55.5 85.  45.8]

In [4]:
# Creating dataframe by passing a numpy array
import pandas as pd
dates= pd.date_range('20140101', periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
# Creating a dataframe by passing a dict that can be converted to series
df2= pd.DataFrame({'A':1,
                   'B': pd.Timestamp('20130102'),
                   'C': pd.Series(1,index=list(range(4)),dtype='float32'),
                   'D': np.array([3]*4,dtype='int32'),
                   'E':pd.Categorical(["test","train","test",'train']),
                   'F': 'foo'
                   })
df2

   A          B    C  D      E    F
0  1 2013-01-02  1.0  3   test  foo
1  1 2013-01-02  1.0  3  train  foo
2  1 2013-01-02  1.0  3   test  foo
3  1 2013-01-02  1.0  3  train  foo

# DataFrame

In [6]:
import pandas as pd
names= pd.Series({'students':'Maria','bought': 'pencil','cost':30})
names_1 = pd.Series({'students':'Susan','bought': 'pen','cost':70})
names_2 = pd.Series({'students':'Kevin','bought': 'eraser','cost':20})
df=pd.DataFrame([names, names_1,names_2],index=['shop 1', 'shop 2','shop 2'])
df.head()

       students  bought  cost
shop 1    Maria  pencil    30
shop 2    Susan     pen    70
shop 2    Kevin  eraser    20

In [7]:
# using loc to extract values from the dataframe
df.loc['shop 2']

       students  bought  cost
shop 2    Susan     pen    70
shop 2    Kevin  eraser    20

In [10]:
# using loc for only a particular column
df.loc['shop 2','students']

shop 2    Susan
shop 2    Kevin
Name: students, dtype: object

In [11]:
#display two or more columns along the index
df.loc[:,['cost','students']]

        cost students
shop 1    30    Maria
shop 2    70    Susan
shop 2    20    Kevin

In [14]:
#adding columns to data frame
df['place']= ['mall', 'road', 'chowk']
df

       students  bought  cost  place
shop 1    Maria  pencil    30   mall
shop 2    Susan     pen    70   road
shop 2    Kevin  eraser    20  chowk

In [16]:
#Renaming a column name
df.rename(columns={'place':'location','students':'Students'})

       Students  bought  cost location
shop 1    Maria  pencil    30     mall
shop 2    Susan     pen    70     road
shop 2    Kevin  eraser    20    chowk